# -*- encoding: utf-8 -*-
{
    'name': 'Asterisk Calls Project',
    'version': '1.1',
    'author': 'Odooist',
    'price': 100,
    'currency': 'EUR',
    'maintainer': 'Odooist',
    'support': 'odooist@gmail.com',
    'license': 'OPL-1',
    'category': 'Phone',
    'summary': 'Asterisk Calls Project integration',
    'description': "",
    'depends': ['project', 'asterisk_calls', 'asterisk_common'],
    'data': [
        'views/project.xml',
        'views/task.xml',
        'views/call.xml',
        'views/channel.xml',
        'views/resources.xml',
        'security/agent.xml',
    ],
    'demo': [],
    "qweb": ['static/src/xml/*.xml'],
    'installable': True,
    'application': False,
    'auto_install': False,
    'images': [
        'static/description/active_calls.png',
        'static/description/call_history.png',
        'static/description/cdr_create_task.png',
        'static/description/popup.png',
        'static/description/project_buttons.png',
        'static/description/task_buttons.png',
    ],
}
