# ©️ OdooPBX by Odooist, Odoo Proprietary License v1.0, 2020
{
    'name': 'Asterisk PBX SIP',
    'summary': 'SIP peers & trunks management',
    'description': "SIP channel management automation",
    'version': '1.5',
    'category': 'Phone',
    'author': 'Odooist',
    'license': 'OPL-1',
    'price': '0',
    'currency': 'EUR',
    'depends': ['asterisk_base'],
    'installable': True,
    'application': False,
    'auto_install': False,
    'post_init_hook': 'do_post_install',
    'uninstall_hook': 'do_uninstall',
    'data': [
        'security/admin/ir.model.access.xml',
        'security/admin/model_access.xml',
        'security/agent/ir.model.access.xml',
        'security/agent/model_access.xml',
        'security/user_model_access.xml',
        'security/user_record_rules.xml',
        # Views
        'views/extension.xml',
        'views/peer_status.xml',
        'views/peer_registry.xml',
        'views/peer_views.xml',
        'views/peer_user.xml',
        'views/peer_trunk.xml',
        'views/peer_template.xml',
        'views/route.xml',
        'views/route_group.xml',
        'views/user.xml',
        'views/translation.xml',
        'views/ir_cron.xml',
        'views/settings.xml',
        # Wizards
        'wizards/peer.xml',
        # Data
        'data/base_sip_conf_templates.xml',
        'data/peer_templates.xml',
        'data/base_sip_events.xml',
        'data/route_group.xml',
    ],
    'demo': [],
    'qweb': [],
    'images': ['static/description/asterisk_base_sip.png'],
}
